spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.zhku.mh.entities

logging:
  level:
    com:
      zhku:
        mh:
          mapper: debug