spring:
  redis:
    port: 6379
    host: 192.168.43.52
    database: 0
    password: 123456
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0